import type { NextPage } from "next";
import Head from "next/head";

export default function Home({}: NextPage) {
  return (
    <div className="min-h-screen text-theme-text-white bg-theme-bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Main</main>
    </div>
  );
}
